name: dart_pty
description: create pseudo terminal and fork process use dart
version: 0.0.4
author: mengyanshou<906262255@qq.com>
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  win32: ^4.0.0
  signale: ^0.0.6
